version: "3.7"
services:
    api:
        image: golang:1.16-stretch
        entrypoint: cicd/docker/entrypoint.sh
        ports:
            - 3000:3000
        volumes:
            - .:/app
        working_dir: /app
