service: urlshortener

frameworkVersion: '>=1.28.0 <2.0.0'

custom:
    dynamoTable: urls-shortener-${self:provider.stage}

provider:
    name: aws
    runtime: go1.x
    stage: prod
    region: ap-southeast-2
    memorySize: 128
    timeout: 10

package:
    exclude:
        - ./**
    include:
        - ./bin/**

functions:
    app:
        handler: bin/url-shortener
        events:
            - http: ANY /
            - http: ANY {proxy+}

resources:
    Resources:
        UrlShortenerDynamoDBTable:
            Type: AWS::DynamoDB::Table
            Properties:
                TableName: ${self:custom.dynamoTable}
                AttributeDefinitions:
                    -
                        AttributeName: slug
                        AttributeType: S
                KeySchema:
                    -
                        AttributeName: slug
                        KeyType: HASH
                ProvisionedThroughput:
                    ReadCapacityUnits: 1
                    WriteCapacityUnits: 1
